name: nextcloud
repoURL: https://nextcloud.github.io/helm/
targetRevision: 7.0.4
chart: nextcloud
namespace: infra
values: |
    nextcloud:
        host: drive.oprimogus.xyz
        trustedDomains:
            - drive.oprimogus.xyz
    service:
        port: 80
    ingress:
        enabled: true
        className: traefik
        path: /
        pathType: Prefix
        tls:
          - hosts:
              - drive.oprimogus.xyz
            secretName: cert-tls
    persistence:
        enabled: true
        storageClass: longhorn-retained
        accessMode: ReadWriteOnce
        size: 10Gi
        nextcloudData:
            enabled: true
            storageClass: longhorn-retained
            accessMode: ReadWriteOnce
            size: 200Gi
        


