name: servarr
repoURL: https://charts.kubito.dev
targetRevision: 1.2.2
chart: kubitodev/servarr
namespace: servarr
values: |
    jellyfin:
      image:
        tag: "10.10.6"
      persistence:
        config:
          enabled: true
          isPvc: true
          storageClass: "longhorn"
          accessModes: ReadWriteOnce
          size: 4Gi
        media:
          enabled: true
          isPvc: true
          storageClass: "longhorn"
          accessModes: ReadWriteOnce
          size: 500Gi
    
    sonarr:
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessModes: ReadWriteOnce
        size: 2Gi
    
    qbittorrent:
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessModes: ReadWriteOnce
        size: 2Gi
        
    prowlarr:
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessModes: ReadWriteOnce
        size: 2Gi
        
    jellyseerr:
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessModes: ReadWriteOnce
        size: 2Gi
        
    bazarr:
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessModes: ReadWriteOnce
        size: 2Gi
        
    radarr:
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessModes: ReadWriteOnce
        size: 2Gi
    
    lidarr:
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessModes: ReadWriteOnce
        size: 2Gi
        
    cleanuparr:
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessModes: ReadWriteOnce
        size: 1Gi
