name: servarr
repoURL: https://charts.kubito.dev
targetRevision: 1.2.2
chart: servarr
namespace: servarr
values: |
    jellyfin:
      image:
        tag: "10.10.6"
      persistence:
        config:
          enabled: true
          isPvc: true
          storageClass: "longhorn"
          accessModes: ReadWriteOnce
          size: 4Gi
        media:
          enabled: true
          isPvc: true
          storageClass: "longhorn"
          accessModes: ReadWriteOnce
          size: 500Gi
      ingress:
        enabled: true
        path: /jellyfin
        hosts:
          - oprimoguslab.xyz

    
    sonarr:
      ingress:
        enabled: true
        path: /sonarr
        hosts:
          - oprimoguslab.xyz
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessModes: ReadWriteOnce
        size: 2Gi
    
    qbittorrent:
      ingress:
        enabled: true
        path: /qbittorrent
        hosts:
          - oprimoguslab.xyz
      initContainers:
        - name: fix-perms
          image: busybox
          command:
            - sh
            - -c
            - chown -R 1000:1000 /media && chmod -R 775 /media
          volumeMounts:
            - name: media
              mountPath: /media
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessModes: ReadWriteOnce
        size: 2Gi
        
    prowlarr:
      ingress:
        enabled: true
        path: /prowlarr
        hosts:
          - oprimoguslab.xyz
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessModes: ReadWriteOnce
        size: 2Gi
        
    jellyseerr:
      ingress:
        enabled: true
        path: /jellyseerr
        hosts:
          - oprimoguslab.xyz
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessModes: ReadWriteOnce
        size: 2Gi
        
    bazarr:
      ingress:
        enabled: true
        path: /bazarr
        hosts:
          - oprimoguslab.xyz
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessModes: ReadWriteOnce
        size: 2Gi
        
    radarr:
      ingress:
        enabled: true
        path: /radarr
        hosts:
          - oprimoguslab.xyz
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessModes: ReadWriteOnce
        size: 2Gi
    
    lidarr:
      ingress:
        enabled: true
        path: /lidarr
        hosts:
          - oprimoguslab.xyz
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessModes: ReadWriteOnce
        size: 2Gi
        
    cleanuparr:
      ingress:
        enabled: true
        path: /cleanuparr
        hosts:
          - oprimoguslab.xyz
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessModes: ReadWriteOnce
        size: 1Gi
