apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-apps-charts
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/oprimogus/flyfood-gitops.git
      revision: main
      files:
      - path: k8s/operators/*
  template:
    metadata:
      name: 'operator-{{path.basename}}'
      namespace: infra
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        chart: '{{chart}}'
        helm:
          values: |
            {{values}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
