apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare-prd
spec:
  acme:
    email: gustavo081900@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - dns01:
        cloudflare:
          email: gustavo081900@gmail.com
          apiTokenSecretRef:
            name: infra/cloudflared
            key: dns-api-token
