apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: prd
spec:
  secretName: cert-tls
  issuerRef:
    name: letsencrypt-cloudflare-prd
    kind: ClusterIssuer
  commonName: oprimoguslab.xyz
  dnsNames:
  - oprimoguslab.xyz
  - auth.oprimoguslab.xyz
  - drive.oprimoguslab.xyz
