apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: prd
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "prd,dev,infra"
  secretName: cert-tls
  issuerRef:
    name: letsencrypt-cloudflare-prd
    kind: ClusterIssuer
  dnsNames:
  - oprimoguslab.xyz
  - auth.oprimoguslab.xyz
  - drive.oprimoguslab.xyz
