name: transmission
repoURL: https://utkuozdemir.org/helm-charts
targetRevision: 2.5.0
chart: transmission-openvpn
namespace: jellyfin
values: |
    image:
        repository: lscr.io/linuxserver/transmission
        tag: "latest"
        pullPolicy: IfNotPresent
    persistence:
        enabled: true
        isPvc: true
        # existingClaim: "jellyfin-data"
        storageClass: longhorn
        size: 500Gi    
    env: 
      # OPENVPN_PROVIDER: my_value
      # CREATE_TUN_DEVICE: "true"
      TRANSMISSION_SPEED_LIMIT_UP: "2048"
      PUID: "1000"
      PGID: "1000"

