name: transmission
chart: oci://ghcr.io/lexfrei/charts/transmission
targetRevision: 1.2.0
namespace: jellyfin
values: |
    env:
        TZ: "America/Sao_Paulo"
    persistence:
        config:
            enabled: true
            storageClassName: "longhorn"
            size: 1Gi
        downloads:
            enabled: true
            type: pvc
            storageClassName: "longhorn"
            accessMode: ReadWriteMany
            size: 500Gi
            # existingClaim must be empty to create a new PVC
            # existingClaim: ""

