name: transmission
repoURL: https://utkuozdemir.org/helm-charts
targetRevision: 2.5.0
chart: transmission-openvpn
namespace: jellyfin
values: |
    image:
        repository: lscr.io/linuxserver/transmission
        tag: "latest"
        pullPolicy: IfNotPresent
    env:
        PUID: "1000"
        PGID: "1000"
        TZ: "America/Sao_Paulo"
    persistence:
        enabled: true
        isPvc: true
        # existingClaim: "jellyfin-data"
        storageClass: longhorn
        size: 500Gi
    
    hostNetwork: true
    hostPort:
      enabled: true
      port: 9091

    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

